header:
  license:
    content: |
      SPDX-License-Identifier: Apache-2.0
  paths-ignore:
    - 'target'
    - '**/*.toml'
    - '**/*.lock'
    - '**/*.yml'
    - '**/*.md'
    - 'CHANGELOG'
    - 'LICENSE'
    - '.gitignore'
    - '.github'
    - 'src/lib/state'

  comment: on-failure
